#!/usr/bin/env sh

# directory containing NetCDF files
inputdir="$HOME/data/0_original"
# directory to put JPEG files
outputdir="$HOME/data/1_jpeg"
# quality
quality=60
# python from current environment
PYTHON="/usr/bin/env python"
# fallback to jpg
FALLBACK_EXT=".jpg"

# auto-setting variables
inputdir="${1:-$inputdir}"
outputdir="${2:-$outputdir}"
quality="${3:-$quality}"

[ ! -d "$inputdir" ] && echo Input folder does not exist! && exit 1
[ ! -d "$outputdir" ] && mkdir -p $outputdir

ncfiles=$(ls $inputdir/*.nc)
[ -z "$ncfiles" ] && echo "No files in input "

for file in $ncfiles
do
  outfilename="$(basename $file)"
  outname="${outfilename%.*}"
  [ $(echo "$outfilename" | grep "\." 2>/dev/null) ] && outext=".${outfilename##*.}"
  if [ -z $outext ] || [ $outext = ".nc" ]
  then
    outext=$FALLBACK_EXT
  fi
  outfile="$outputdir/$outname$outext"

  echo "### Converting ###"
  echo "# $file"
  echo "# to"
  echo "# $outfile"
  echo "##################"

  [ -f $file ] && $PYTHON nc2jpg/nc2jpg.py $file -o $outfile -q $quality

  echo "\n"
done
